#datset
dataset: 'squad'
num_workers: 4

#model param
model_name: 'distilbert-base-cased-distilled-squad'
lr: 3e-5
batch_size: 232
num_epochs: 5

#training param
devices: 2
num_nodes: 1
accelerator: 'gpu'
precision: 16
strategy: 'ddp'
checkpoint: False


