#datset
dataset: 'squad'
num_workers: 4

#model param
model_name: 'bert-base-uncased'
lr: 3e-5
batch_size: 16
num_epochs: 20

#training param
device: 2
accelerator: 'gpu'
precision: 16
strategy: 'ddp'



